version: "3"

services:
  app:
    build: .
    command: npm start
    ports:
      - "8000:8000"
    volumes:
      - .:/app/
      - /app/node_modules

  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: stock
      POSTGRES_PASSWORD: stockapp
      POSTGRES_DB: stock
